### ISSUE TITLE
When predict ner datas use ner samples [KeyError: 'ner'] has been occured

### ISSUE THREAD

**Issue by gherao** [heartexlabs/label-studio-transformers#14]
When predict ner datas,next error has been occured,I print tasks,I found out that the place where it should be 'ner' was programmed with  '$undefined$' ,

tasks data:
```
tasks:[{'id': 17, 'data': {'$undefined$': 'This work proposes a novel adaptation of a pretrained sequence-to-sequence model to the task of document ranking.'}, 'meta': {}, 'created_at': '2021-07-05T02:30:36.230799Z', 'updated_at': '2021-07-05T02:30:36.230834Z', 'is_labeled': True, 'overlap': 1, 'project': 10, 'file_upload': 6, 'annotations': [{'id': 17, 'created_username': ' admin@123.com, 1', 'created_ago': '0\xa0minutes', 'completed_by': 1, 'result': [{'value': {'start': 54, 'end': 74, 'text': 'sequence-to-sequence', 'labels': ['ORG']}, 'id': 'FA_HTHugoH', 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'was_cancelled': False, 'ground_truth': False, 'created_at': '2021-07-05T02:38:39.940285Z', 'updated_at': '2021-07-05T02:38:39.940321Z', 'lead_time': 11.491, 'task': 17}], 'predictions': []}]
```
error:
```
[2021-07-05 10:38:40,048] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/model.py", line 274, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/workspace/label-studio/label-studio-transformers/ner-backend-test/ner.py", line 369, in predict
    texts = [task['data'][self.value] for task in tasks]
  File "/workspace/label-studio/label-studio-transformers/ner-backend-test/ner.py", line 369, in <listcomp>
    texts = [task['data'][self.value] for task in tasks]
KeyError: 'ner'

Traceback (most recent call last):
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/workspace/label-studio/label-studio-ml-backend/label_studio_ml/model.py", line 274, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/workspace/label-studio/label-studio-transformers/ner-backend-test/ner.py", line 369, in predict
    texts = [task['data'][self.value] for task in tasks]
  File "/workspace/label-studio/label-studio-transformers/ner-backend-test/ner.py", line 369, in <listcomp>
    texts = [task['data'][self.value] for task in tasks]
KeyError: 'ner'
```

**Comment by gherao** [comment]
I temporarily solved this problem, the solution:
```
texts = [task['data'][self.value] for task in tasks]
```
to
```
texts = [task['data'].get(self.value) or task['data'].get(DATA_UNDEFINED_NAME) for task in tasks]
```

To use [DATA_UNDEFINED_NAME], need the following dependencies
```
from label_studio.core.settings.base import DATA_UNDEFINED_NAME
```
thanks
